application: arcateca
version: 1
runtime: python
api_version: 1

handlers:
- url: /console/static
  static_dir: console/app/view/static

- url: /console.*
  script: console/app/console.py
  login: admin

- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.py
  login: admin

- url: /.*
  script: main.py
